SET(CMAKE_SYSTEM_NAME Generic)
SET(CMAKE_SYSTEM_VERSION 1)
SET(CMAKE_C_COMPILER [==[gcc]==] CACHE STRING "")
SET(CMAKE_CXX_COMPILER [==[g++]==] CACHE STRING "")
SET(CMAKE_LINKER [==[gcc]==] CACHE STRING "")
SET(CMAKE_RANLIB [==[ranlib]==] CACHE STRING "")
SET(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
SET(CMAKE_C_FLAGS [==[-Werror -Wall -Wextra -pedantic -g3 -Og -U_FORTIFY_SOURCE -std=gnu11 -m32 -ffunction-sections -fdata-sections -DDEBUG_ASSERT_VERBOSE -DRIOT_APPLICATION=\""riot-relic"\" -DBOARD_NATIVE=\"native\" -DRIOT_BOARD=BOARD_NATIVE -DCPU_NATIVE=\"native\" -DRIOT_CPU=CPU_NATIVE -DMCU_NATIVE=\"native\" -DRIOT_MCU=MCU_NATIVE -fwrapv -Wstrict-overflow -fno-common -ffunction-sections -fdata-sections -Wall -Wextra -Wmissing-include-dirs -DNDEBUG -fno-delete-null-pointer-checks -fdiagnostics-color -Wstrict-prototypes -Wold-style-definition -gz -Wformat=2 -Wformat-overflow -Wformat-truncation -include '/root/Documents/Relic-RIOT-Integration/bin/native/riotbuild/riotbuild.h' -Wno-gnu-zero-variadic-macro-arguments -Wno-unused-function -Wno-newline-eof]==] CACHE STRING "")
SET(CMAKE_EXE_LINKER_FLAGS [==[]==] CACHE STRING "")
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
